---
name: Ruby Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # Pin to version 1.237.0
        uses: ruby/setup-ruby@eaecf785f6a34567a6d97f686bbb7bccc1ac1e5c
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
